const $=(s,r=document)=>r.querySelector(s);
const WA='5548996752532';
const state={lang:document.documentElement.lang?.toLowerCase().startsWith('pt')?'pt':'es',listening:false,busy:false,lead:{company:'',businessType:'',mainPain:'',channels:[],approxVolume:'',currentTools:[],manualTasks:[],expectedResult:'',recommendedFirstAutomation:'',recommendedPackage:'',purchaseIntent:'low',nextStep:''},messages:[]};
const copy={es:{badge:'Conversá con V2 AI',title:'V2 AI · Consultor Comercial',ready:'Listo para conversar',listening:'Escuchando…',thinking:'Pensando…',speaking:'Hablando…',start:'Iniciar conversación',stop:'Detener micrófono',placeholder:'Escribí o hablá…',hello:'Hola, soy V2 AI. Puedo entender cómo funciona tu negocio y mostrarte dónde V2 Studio podría ayudarte. ¿Qué tipo de negocio tenés?',lead:'Diagnóstico en vivo',wa:'Continuar por WhatsApp',hint:'Micrófono del navegador + Gemini 2.5 Flash',unsupported:'Tu navegador no permite reconocimiento de voz. Podés usar el chat escrito igualmente.'},pt:{badge:'Converse com a V2 AI',title:'V2 AI · Consultor Comercial',ready:'Pronto para conversar',listening:'Ouvindo…',thinking:'Pensando…',speaking:'Falando…',start:'Iniciar conversa',stop:'Parar microfone',placeholder:'Escreva ou fale…',hello:'Olá, eu sou a V2 AI. Posso entender como seu negócio funciona e mostrar onde a V2 Studio pode ajudar. Que tipo de negócio você tem?',lead:'Diagnóstico ao vivo',wa:'Continuar no WhatsApp',hint:'Microfone do navegador + Gemini 2.5 Flash',unsupported:'Seu navegador não permite reconhecimento de voz. Você pode usar o chat escrito normalmente.'}};
const t=()=>copy[state.lang];
const root=document.createElement('div');root.id='v2ai-root';root.innerHTML=`<div class="v2ai-launch"><button class="v2ai-orb" aria-label="V2 AI"><span class="v2ai-core"></span></button><div class="v2ai-badge"><b>V2 AI</b><span>${t().badge}</span></div></div><section class="v2ai-panel"><header class="v2ai-head"><div class="v2ai-mini"></div><div><strong>${t().title}</strong><small><i>●</i> <span class="v2ai-status">${t().ready}</span></small></div><button class="v2ai-close">×</button></header><div class="v2ai-grid"><div class="v2ai-main"><div class="v2ai-stage"><button class="v2ai-bigorb" aria-label="Voz"><span class="v2ai-stage-core"></span></button><button class="v2ai-call">🎙 ${t().start}</button><small>${t().hint}</small></div><div class="v2ai-messages"></div><div class="v2ai-compose"><input class="v2ai-input" placeholder="${t().placeholder}" autocomplete="off"><button class="v2ai-send">➜</button></div></div><aside class="v2ai-side"><div class="v2ai-side-title"><span>${t().lead}</span><em>LIVE</em></div><div class="v2ai-lead"></div><button class="v2ai-wa" hidden>${t().wa}</button></aside></div></section>`;document.body.appendChild(root);
const panel=$('.v2ai-panel',root),orb=$('.v2ai-orb',root),bigOrb=$('.v2ai-bigorb',root),call=$('.v2ai-call',root),statusEl=$('.v2ai-status',root),msgs=$('.v2ai-messages',root),input=$('.v2ai-input',root),send=$('.v2ai-send',root),leadBox=$('.v2ai-lead',root),waBtn=$('.v2ai-wa',root),closeBtn=$('.v2ai-close',root);
let recognition=null,voiceMode=false,recognitionRunning=false;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function addMessage(text,who='ai'){if(!text)return;state.messages.push({who,text});const d=document.createElement('div');d.className='v2ai-msg '+who;d.textContent=text;msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight}
function setStatus(s){statusEl.textContent=s}
function mergeLead(p={}){for(const k of Object.keys(state.lead)){const v=p[k];if(v===undefined||v===null||v==='')continue;if(Array.isArray(v)){if(v.length)state.lead[k]=[...new Set([...(state.lead[k]||[]),...v])]}else state.lead[k]=v}renderLead()}
function packageLabel(v){return ({pacote_1:'Presença & Atendimento',pacote_2:'Business Automation',pacote_3:'Ecossistema Digital & IA'})[v]||v||''}
function renderLead(){const L=state.lead;const rows=[[state.lang==='pt'?'Negócio':'Negocio',L.businessType||L.company],[state.lang==='pt'?'Dor':'Problema',L.mainPain],[state.lang==='pt'?'Canais':'Canales',(L.channels||[]).join(', ')],[state.lang==='pt'?'Volume':'Volumen',L.approxVolume],[state.lang==='pt'?'Ferramentas':'Herramientas',(L.currentTools||[]).join(', ')],[state.lang==='pt'?'1ª automação':'1ª automatización',L.recommendedFirstAutomation],[state.lang==='pt'?'Pacote':'Paquete',packageLabel(L.recommendedPackage)],[state.lang==='pt'?'Intenção':'Intención',L.purchaseIntent]].filter(x=>x[1]);leadBox.innerHTML=rows.length?rows.map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join(''):`<p>${state.lang==='pt'?'Ainda coletando informações…':'Todavía recopilando información…'}</p>`;if(L.purchaseIntent==='high'||L.nextStep==='whatsapp')waBtn.hidden=false}
function whatsapp(){const L=state.lead;const txt=`V2 AI — ${state.lang==='pt'?'Diagnóstico':'Diagnóstico'}\n${L.company||''} ${L.businessType||''}\n${state.lang==='pt'?'Dor':'Problema'}: ${L.mainPain||''}\n${state.lang==='pt'?'Canais':'Canales'}: ${(L.channels||[]).join(', ')}\n${state.lang==='pt'?'Volume':'Volumen'}: ${L.approxVolume||''}\n${state.lang==='pt'?'Sugestão':'Sugerencia'}: ${L.recommendedFirstAutomation||''}`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(txt)}`,'_blank','noopener')}
function chooseVoice(){const vs=speechSynthesis.getVoices();const prefix=state.lang==='pt'?'pt':'es';return vs.find(v=>v.lang?.toLowerCase().startsWith(prefix))||vs[0]}
function speak(text,thenListen=true){if(!('speechSynthesis'in window)){if(thenListen&&voiceMode)startRecognition();return}stopRecognition();speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=state.lang==='pt'?'pt-BR':'es-AR';const v=chooseVoice();if(v)u.voice=v;u.rate=1.02;u.onstart=()=>{setStatus(t().speaking);orb.classList.add('speaking');bigOrb.classList.add('speaking')};u.onend=()=>{orb.classList.remove('speaking');bigOrb.classList.remove('speaking');setStatus(t().ready);if(thenListen&&voiceMode)setTimeout(startRecognition,250)};u.onerror=()=>{setStatus(t().ready);if(thenListen&&voiceMode)setTimeout(startRecognition,250)};speechSynthesis.speak(u)}
async function sendMessage(text,fromVoice=false){text=String(text||'').trim();if(!text||state.busy)return;state.busy=true;stopRecognition();addMessage(text,'user');input.value='';setStatus(t().thinking);try{const r=await fetch('/api/gemini-chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:text,history:state.messages.slice(0,-1),lead:state.lead,lang:state.lang})});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||'Gemini error');mergeLead(d.lead||{});addMessage(d.reply,'ai');if(d.openWhatsapp)waBtn.hidden=false;speak(d.reply,true)}catch(e){console.error(e);const msg=state.lang==='pt'?'Não consegui consultar a IA agora. Tente novamente em alguns segundos.':'No pude consultar la IA ahora. Probá de nuevo en unos segundos.';addMessage(msg,'ai');speak(msg,true)}finally{state.busy=false}}
function buildRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return null;const r=new SR();r.lang=state.lang==='pt'?'pt-BR':'es-AR';r.interimResults=false;r.continuous=false;r.maxAlternatives=1;r.onstart=()=>{recognitionRunning=true;setStatus(t().listening);orb.classList.add('listening');bigOrb.classList.add('listening')};r.onresult=e=>{const text=e.results?.[0]?.[0]?.transcript||'';if(text)sendMessage(text,true)};r.onerror=e=>{recognitionRunning=false;orb.classList.remove('listening');bigOrb.classList.remove('listening');if(e.error!=='aborted'&&e.error!=='no-speech')addMessage(state.lang==='pt'?'Não consegui ouvir. Tente novamente.':'No pude escucharte. Probá de nuevo.','ai');setStatus(t().ready)};r.onend=()=>{recognitionRunning=false;orb.classList.remove('listening');bigOrb.classList.remove('listening');if(voiceMode&&!state.busy&&!speechSynthesis.speaking)setStatus(t().ready)};return r}
function startRecognition(){if(!voiceMode||state.busy||speechSynthesis.speaking)return;if(!recognition)recognition=buildRecognition();if(!recognition){voiceMode=false;call.textContent='🎙 '+t().start;addMessage(t().unsupported,'ai');return}recognition.lang=state.lang==='pt'?'pt-BR':'es-AR';try{if(!recognitionRunning)recognition.start()}catch{}}
function stopRecognition(){if(recognition&&recognitionRunning){try{recognition.abort()}catch{}}recognitionRunning=false;orb.classList.remove('listening');bigOrb.classList.remove('listening')}
function toggleVoice(){voiceMode=!voiceMode;if(voiceMode){call.textContent='■ '+t().stop;if(!state.messages.length){addMessage(t().hello,'ai');speak(t().hello,true)}else startRecognition()}else{stopRecognition();speechSynthesis.cancel();call.textContent='🎙 '+t().start;setStatus(t().ready)}}
orb.onclick=()=>panel.classList.toggle('open');bigOrb.onclick=toggleVoice;call.onclick=toggleVoice;closeBtn.onclick=()=>{panel.classList.remove('open');voiceMode=false;stopRecognition();speechSynthesis.cancel()};send.onclick=()=>sendMessage(input.value,false);input.addEventListener('keydown',e=>{if(e.key==='Enter')sendMessage(input.value,false)});waBtn.onclick=whatsapp;renderLead();
window.speechSynthesis?.getVoices();
