const $=(s,r=document)=>r.querySelector(s);
const WA='5548996752532';
const MODEL='gemini-3.1-flash-live-preview';
const state={lang:'es',connected:false,ready:false,lead:{company:'',businessType:'',mainPain:'',channels:[],approxVolume:'',currentTools:[],manualTasks:[],expectedResult:'',recommendedFirstAutomation:'',recommendedPackage:'',purchaseIntent:'low',nextStep:''},messages:[]};
let kb={}; try{kb=await fetch('/knowledge-base.json',{cache:'no-store'}).then(r=>r.json())}catch(e){console.warn('KB unavailable',e)}
const copy={es:{badge:'Conversá con V2 AI',title:'V2 AI · Consultor Comercial',ready:'Listo para conversar',connecting:'Conectando con Gemini…',live:'Escuchando · podés interrumpirme',speaking:'V2 AI está hablando…',start:'Iniciar conversación',stop:'Terminar',placeholder:'Escribí o hablá…',welcome:'¡Hola! Soy V2 AI, el consultor comercial de V2 Studio. Puedo entender cómo funciona tu negocio y mostrarte dónde podríamos ayudarte. ¿Qué tipo de negocio tenés?',lead:'Diagnóstico en vivo',wa:'Continuar por WhatsApp',kb:'Base de conocimiento V2 Studio',hint:'Voz Gemini Live · PT/ES · closer consultivo'},pt:{badge:'Converse com a V2 AI',title:'V2 AI · Consultor Comercial',ready:'Pronto para conversar',connecting:'Conectando ao Gemini…',live:'Ouvindo · você pode me interromper',speaking:'V2 AI está falando…',start:'Iniciar conversa',stop:'Encerrar',placeholder:'Escreva ou fale…',welcome:'Olá! Eu sou a V2 AI, consultor comercial da V2 Studio. Posso entender como seu negócio funciona e mostrar onde podemos ajudar. Que tipo de negócio você tem?',lead:'Diagnóstico ao vivo',wa:'Continuar no WhatsApp',kb:'Base de conhecimento V2 Studio',hint:'Voz Gemini Live · PT/ES · closer consultivo'}};
const t=()=>copy[state.lang];
const root=document.createElement('div');root.id='v2ai-root';root.innerHTML=`<div class="v2ai-launch"><button class="v2ai-orb" aria-label="V2 AI"><canvas width="140" height="140"></canvas><span class="v2ai-core"></span></button><div class="v2ai-badge"><b>V2 AI</b><span>${t().badge}</span></div></div><section class="v2ai-panel" aria-label="V2 AI"><header class="v2ai-head"><div class="v2ai-mini"></div><div><strong>${t().title}</strong><small><i>●</i> <span class="v2ai-status">${t().ready}</span></small></div><button class="v2ai-close" aria-label="Cerrar">×</button></header><div class="v2ai-grid"><div class="v2ai-main"><div class="v2ai-stage"><button class="v2ai-bigorb" aria-label="Iniciar voz"><canvas width="260" height="260"></canvas><span class="v2ai-stage-core"></span></button><button class="v2ai-call">🎙 ${t().start}</button><small>${t().hint}</small></div><div class="v2ai-messages"></div><div class="v2ai-compose"><input class="v2ai-input" placeholder="${t().placeholder}" autocomplete="off"><button class="v2ai-send">➜</button></div></div><aside class="v2ai-side"><div class="v2ai-side-title"><span>${t().lead}</span><em>LIVE</em></div><div class="v2ai-lead"></div><button class="v2ai-wa" hidden>${t().wa}</button><button class="v2ai-kb-btn">${t().kb}</button></aside></div></section>`;document.body.appendChild(root);
const panel=$('.v2ai-panel',root),orb=$('.v2ai-orb',root),bigOrb=$('.v2ai-bigorb',root),call=$('.v2ai-call',root),statusEl=$('.v2ai-status',root),msgs=$('.v2ai-messages',root),input=$('.v2ai-input',root),send=$('.v2ai-send',root),leadBox=$('.v2ai-lead',root),waBtn=$('.v2ai-wa',root),closeBtn=$('.v2ai-close',root),kbBtn=$('.v2ai-kb-btn',root);
let ws=null,micStream=null,micCtx=null,processor=null,source=null,outCtx=null,audioSources=new Set(),nextAudioTime=0,outputTranscript='',inputTranscript='',startedGreeting=false;
function setStatus(s){statusEl.textContent=s}
function addMessage(text,who='ai'){if(!text)return;state.messages.push({who,text});const d=document.createElement('div');d.className='v2ai-msg '+who;d.textContent=text;msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight}
function setLang(l){if(l!=='es'&&l!=='pt')return;state.lang=l;input.placeholder=t().placeholder;waBtn.textContent=t().wa;kbBtn.textContent=t().kb;renderLead()}
function renderLead(){const L=state.lead;const empty=state.lang==='pt'?'Ainda coletando informações…':'Todavía recopilando información…';const rows=[[state.lang==='pt'?'Negócio':'Negocio',L.businessType||L.company],[state.lang==='pt'?'Dor principal':'Problema principal',L.mainPain],[state.lang==='pt'?'Canais':'Canales',(L.channels||[]).join(', ')],[state.lang==='pt'?'Volume':'Volumen',L.approxVolume],[state.lang==='pt'?'Ferramentas':'Herramientas',(L.currentTools||[]).join(', ')],[state.lang==='pt'?'1ª automação':'1ª automatización',L.recommendedFirstAutomation],[state.lang==='pt'?'Pacote':'Paquete',packageLabel(L.recommendedPackage)],[state.lang==='pt'?'Intenção':'Intención',intentLabel(L.purchaseIntent)]].filter(x=>x[1]);leadBox.innerHTML=rows.length?rows.map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join(''):`<p>${empty}</p>`;if(L.purchaseIntent==='high'||L.nextStep==='whatsapp')waBtn.hidden=false}
function packageLabel(v){return v==='pacote_1'?'Presença & Atendimento':v==='pacote_2'?'Business Automation':v==='pacote_3'?'Ecossistema Digital & IA':''}
function intentLabel(v){if(!v)return'';return state.lang==='pt'?({low:'Baixa',medium:'Média',high:'Alta'}[v]||v):({low:'Baja',medium:'Media',high:'Alta'}[v]||v)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function mergeLead(args={}){for(const k of Object.keys(state.lead)){const v=args[k];if(v===undefined||v===null||v==='')continue;if(Array.isArray(v)){if(v.length)state.lead[k]=[...new Set([...(state.lead[k]||[]),...v])]}else state.lead[k]=v}renderLead();saveSession()}
function saveSession(){try{sessionStorage.setItem('v2ai-lead',JSON.stringify(state.lead))}catch{}}
try{const saved=JSON.parse(sessionStorage.getItem('v2ai-lead')||'null');if(saved)state.lead={...state.lead,...saved}}catch{}renderLead();
function systemPrompt(){return `# V2 AI — CONSULTOR COMERCIAL POR VOZ\n\nIDENTIDADE\nVocê é V2 AI, consultor comercial virtual da V2 Studio, Florianópolis, Santa Catarina. Sua função é conversar como um bom consultor humano: entender o negócio, detectar um problema real, recomendar UMA primeira solução e gerar um próximo passo concreto. Não aja como FAQ nem como catálogo.\n\nIDIOMA\nDetecte o idioma do visitante. Português -> português brasileiro natural. Espanhol -> espanhol natural rioplatense/neutro.\n\nESTILO DE VOZ\nHumano, profissional, próximo, seguro, claro, consultivo e breve. Fale normalmente em 1 a 3 frases. Faça SOMENTE UMA pergunta por turno. Não leia listas. Permita interrupções.\n\nPRINCÍPIO COMERCIAL\nNão vendemos tecnologia por tecnologia. Identificamos onde a empresa perde tempo, clientes ou dinheiro e propomos uma solução simples para corrigir isso. Fale de resultado antes de tecnologia.\n\nORDEM CONVERSACIONAL\n1 tipo de negócio; 2 principal problema; 3 canais; 4 volume; 5 quem atende; 6 ferramentas apenas se relevante; 7 impacto; 8 resumo; 9 UMA primeira solução pequena; 10 objeções; 11 intenção de compra; 12 WhatsApp. Pule o que já foi respondido.\n\nPREÇOS\nNunca invente preço. Modelo: implantação + mensalidade de suporte/manutenção/melhorias; depende de canais, volume, integrações e complexidade.\n\nINTEGRAÇÕES\nPara Booking, Airbnb, PMS ou channel manager: integrações dependem da disponibilidade da API e das permissões da conta. Nunca prometa antes de validar.\n\nCLOSER\nUse: problema confirmado -> impacto -> solução pequena -> próximo passo concreto. Nunca pressione, nunca use escassez falsa e nunca invente case, cliente, estatística ou ROI.\n\nFERRAMENTAS\nSempre que aprender ou atualizar dados comerciais do lead, chame update_lead silenciosamente. Quando o lead pedir contato humano, proposta, orçamento, como começar, demonstrar alta intenção, ou aceitar a recomendação, chame open_whatsapp. Após chamar uma ferramenta, continue a conversa naturalmente.\n\nBASE DE CONHECIMENTO OFICIAL\n${JSON.stringify(kb)}\n\nLEAD ATUAL\n${JSON.stringify(state.lead)}`}
const tools=[{functionDeclarations:[{name:'update_lead',description:'Atualiza a ficha comercial do lead sempre que novas informações forem aprendidas. Chame sem anunciar a ferramenta.',parameters:{type:'OBJECT',properties:{company:{type:'STRING'},businessType:{type:'STRING'},mainPain:{type:'STRING'},channels:{type:'ARRAY',items:{type:'STRING'}},approxVolume:{type:'STRING'},currentTools:{type:'ARRAY',items:{type:'STRING'}},manualTasks:{type:'ARRAY',items:{type:'STRING'}},expectedResult:{type:'STRING'},recommendedFirstAutomation:{type:'STRING'},recommendedPackage:{type:'STRING',description:'pacote_1, pacote_2 ou pacote_3'},purchaseIntent:{type:'STRING',description:'low, medium ou high'},nextStep:{type:'STRING'}}}},{name:'open_whatsapp',description:'Solicita handoff para a equipe humana da V2 Studio pelo WhatsApp quando houver intenção real ou pedido explícito.',parameters:{type:'OBJECT',properties:{reason:{type:'STRING'},summary:{type:'STRING'}}}}]}];
function bytesToB64(int16){const u=new Uint8Array(int16.buffer,int16.byteOffset,int16.byteLength);let s='';for(let i=0;i<u.length;i+=32768)s+=String.fromCharCode(...u.subarray(i,i+32768));return btoa(s)}
function b64ToInt16(s){const bin=atob(s),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return new Int16Array(u.buffer)}
function downsample(input,srcRate,target=16000){if(srcRate===target){const out=new Int16Array(input.length);for(let i=0;i<input.length;i++)out[i]=Math.max(-1,Math.min(1,input[i]))*32767;return out}const ratio=srcRate/target,len=Math.round(input.length/ratio),out=new Int16Array(len);for(let i=0;i<len;i++){const a=Math.floor(i*ratio),b=Math.min(input.length,Math.floor((i+1)*ratio));let sum=0,n=0;for(let j=a;j<b;j++){sum+=input[j];n++}const v=Math.max(-1,Math.min(1,n?sum/n:0));out[i]=v<0?v*32768:v*32767}return out}
async function playAudio(b64){if(!outCtx)outCtx=new AudioContext({sampleRate:24000});if(outCtx.state==='suspended')await outCtx.resume();const pcm=b64ToInt16(b64),buf=outCtx.createBuffer(1,pcm.length,24000),ch=buf.getChannelData(0);for(let i=0;i<pcm.length;i++)ch[i]=pcm[i]/32768;const n=outCtx.createBufferSource();n.buffer=buf;n.connect(outCtx.destination);audioSources.add(n);nextAudioTime=Math.max(nextAudioTime,outCtx.currentTime+.015);n.start(nextAudioTime);nextAudioTime+=buf.duration;n.onended=()=>audioSources.delete(n);orb.classList.add('speaking');bigOrb.classList.add('speaking');setStatus(t().speaking)}
function clearAudio(){for(const s of audioSources){try{s.stop()}catch{}}audioSources.clear();nextAudioTime=outCtx?.currentTime||0;orb.classList.remove('speaking');bigOrb.classList.remove('speaking')}
async function startMic(){micStream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});micCtx=new AudioContext();await micCtx.resume();source=micCtx.createMediaStreamSource(micStream);processor=micCtx.createScriptProcessor(2048,1,1);processor.onaudioprocess=e=>{if(!state.ready||!ws||ws.readyState!==WebSocket.OPEN)return;const pcm=downsample(e.inputBuffer.getChannelData(0),micCtx.sampleRate,16000);ws.send(JSON.stringify({realtimeInput:{audio:{data:bytesToB64(pcm),mimeType:'audio/pcm;rate=16000'}}}))};source.connect(processor);processor.connect(micCtx.destination);orb.classList.add('listening');bigOrb.classList.add('listening');setStatus(t().live)}
function stopMic(){if(processor){try{processor.disconnect()}catch{}processor=null}if(source){try{source.disconnect()}catch{}source=null}if(micStream){micStream.getTracks().forEach(x=>x.stop());micStream=null}if(micCtx){micCtx.close().catch(()=>{});micCtx=null}orb.classList.remove('listening');bigOrb.classList.remove('listening')}
async function connect(){if(state.connected)return;panel.classList.add('open');call.disabled=true;setStatus(t().connecting);try{const r=await fetch('/api/gemini-token',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||'No se pudo obtener token Gemini');const url=`wss://generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1beta.GenerativeService.BidiGenerateContentConstrained?access_token=${encodeURIComponent(d.token)}`;ws=new WebSocket(url);ws.onopen=()=>{ws.send(JSON.stringify({setup:{model:`models/${d.model||MODEL}`,generationConfig:{responseModalities:['AUDIO'],temperature:.7,speechConfig:{voiceConfig:{prebuiltVoiceConfig:{voiceName:'Puck'}}},thinkingConfig:{thinkingLevel:'LOW'}},systemInstruction:{parts:[{text:systemPrompt()}]},tools,inputAudioTranscription:{},outputAudioTranscription:{},contextWindowCompression:{slidingWindow:{}},sessionResumption:{}}}))};ws.onmessage=onMessage;ws.onerror=()=>fail('Gemini Live: error de conexión.');ws.onclose=()=>{if(state.connected)disconnect(false)}}catch(e){console.error(e);fail(state.lang==='pt'?'Não foi possível iniciar a voz Gemini. Verifique a API no Vercel.':'No pude iniciar la voz de Gemini. Verificá la API en Vercel.')}finally{call.disabled=false}}
async function onMessage(ev){let m;try{m=JSON.parse(ev.data)}catch{return}if(m.setupComplete){state.connected=state.ready=true;root.classList.add('connected');call.textContent='■ '+t().stop;await startMic();if(!startedGreeting){startedGreeting=true;sendText(t().welcome,false)}return}if(m.toolCall)handleToolCall(m.toolCall);if(m.sessionResumptionUpdate?.newHandle){try{sessionStorage.setItem('v2ai-resume',m.sessionResumptionUpdate.newHandle)}catch{}}const sc=m.serverContent;if(!sc)return;if(sc.interrupted){clearAudio();setStatus(t().live)}if(sc.inputTranscription?.text){inputTranscript+=sc.inputTranscription.text;if(sc.turnComplete){const q=inputTranscript.trim();if(q){addMessage(q,'user');detectLang(q)}inputTranscript=''}}if(sc.outputTranscription?.text){outputTranscript+=sc.outputTranscription.text}if(sc.modelTurn?.parts){for(const p of sc.modelTurn.parts)if(p.inlineData?.data)await playAudio(p.inlineData.data)}if(sc.turnComplete||sc.generationComplete){const a=outputTranscript.trim();if(a){addMessage(a,'ai');outputTranscript=''}orb.classList.remove('speaking');bigOrb.classList.remove('speaking');if(state.connected)setStatus(t().live)}}
function handleToolCall(tc){const responses=[];for(const fc of tc.functionCalls||[]){let result={ok:true};if(fc.name==='update_lead'){mergeLead(fc.args||{});result={ok:true,lead:state.lead}}else if(fc.name==='open_whatsapp'){mergeLead({purchaseIntent:'high',nextStep:'whatsapp'});waBtn.hidden=false;result={ok:true,message:'WhatsApp CTA is visible for the user.'}}else result={ok:false,error:'unknown_tool'};responses.push({name:fc.name,id:fc.id,response:{result}})}if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify({toolResponse:{functionResponses:responses}}))}
function detectLang(x){const s=x.toLowerCase();if(/\b(voc[eê]|negócio|quero|quanto|atendimento|empresa|vocês|tenho|preciso)\b/.test(s))setLang('pt');else if(/\b(tenés|quiero|cuánto|negocio|empresa|ustedes|tengo|necesito|podés)\b/.test(s))setLang('es')}
function sendText(x,show=true){x=(x||'').trim();if(!x)return;detectLang(x);if(show)addMessage(x,'user');input.value='';if(state.ready&&ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify({realtimeInput:{text:x}}));else addMessage(state.lang==='pt'?'Inicie a conversa por voz para conectar com o Gemini Live.':'Iniciá la conversación por voz para conectar con Gemini Live.','ai')}
function disconnect(closeSocket=true){state.connected=state.ready=false;root.classList.remove('connected');stopMic();clearAudio();if(closeSocket&&ws){try{ws.send(JSON.stringify({realtimeInput:{audioStreamEnd:true}}))}catch{}try{ws.close()}catch{}}ws=null;call.textContent='🎙 '+t().start;setStatus(t().ready)}
function fail(msg){disconnect();addMessage(msg,'ai')}
function openWhatsapp(){const L=state.lead;const lines=state.lang==='pt'?[`Olá equipe V2 Studio! Vim através da V2 AI.`,`Empresa/Tipo: ${L.company||L.businessType||'A definir'}`,`Problema principal: ${L.mainPain||'A definir'}`,`Canais: ${(L.channels||[]).join(', ')||'A definir'}`,`Volume: ${L.approxVolume||'A definir'}`,`Automação sugerida: ${L.recommendedFirstAutomation||'A definir'}`,`Pacote sugerido: ${packageLabel(L.recommendedPackage)||'A definir'}`,`Gostaria de continuar o diagnóstico comercial.`]:[`Hola equipo V2 Studio! Vengo a través de V2 AI.`,`Empresa/Tipo: ${L.company||L.businessType||'A definir'}`,`Problema principal: ${L.mainPain||'A definir'}`,`Canales: ${(L.channels||[]).join(', ')||'A definir'}`,`Volumen: ${L.approxVolume||'A definir'}`,`Automatización sugerida: ${L.recommendedFirstAutomation||'A definir'}`,`Paquete sugerido: ${packageLabel(L.recommendedPackage)||'A definir'}`,`Me gustaría continuar el diagnóstico comercial.`];window.open(`https://wa.me/${WA}?text=${encodeURIComponent(lines.join('\n'))}`,'_blank','noopener')}
orb.onclick=()=>panel.classList.toggle('open');bigOrb.onclick=()=>state.connected?disconnect():connect();call.onclick=()=>state.connected?disconnect():connect();closeBtn.onclick=()=>{panel.classList.remove('open');if(state.connected)disconnect()};send.onclick=()=>sendText(input.value);input.addEventListener('keydown',e=>{if(e.key==='Enter')sendText(input.value)});waBtn.onclick=openWhatsapp;kbBtn.onclick=()=>{const s=state.lang==='pt'?'V2 Studio combina design, web, atendimento e automação com IA. A conversa usa a base comercial oficial para diagnosticar antes de recomendar.':'V2 Studio combina diseño, web, atención y automatización con IA. La conversación usa la base comercial oficial para diagnosticar antes de recomendar.';addMessage(s,'ai')};window.addEventListener('beforeunload',()=>disconnect());
function animateCanvas(canvas,big=false){const c=canvas.getContext('2d');let z=0;function frame(){z+=.025;const w=canvas.width,h=canvas.height,x=w/2,y=h/2;c.clearRect(0,0,w,h);const active=state.connected;const speaking=orb.classList.contains('speaking');const listening=orb.classList.contains('listening');const r=(big?68:38)+(speaking?Math.sin(z*8)*5:listening?Math.sin(z*4)*3:Math.sin(z*2)*1.5);for(let k=3;k>=1;k--){c.beginPath();c.arc(x,y,r+k*11+Math.sin(z*2+k)*3,0,Math.PI*2);c.strokeStyle=`rgba(0,248,0,${active?.10:.04})`;c.lineWidth=1;c.stroke()}const g=c.createRadialGradient(x-r*.28,y-r*.30,r*.05,x,y,r);g.addColorStop(0,'#f3fff3');g.addColorStop(.16,'#00f800');g.addColorStop(.42,'#168b26');g.addColorStop(.72,'#0d2d13');g.addColorStop(1,'#030603');c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fillStyle=g;c.shadowColor='#00f800';c.shadowBlur=active?28:14;c.fill();c.shadowBlur=0;if(active){const bars=big?26:16;for(let i=0;i<bars;i++){const a=(i/bars)*Math.PI*2+z*.6,len=(speaking||listening)?6+Math.abs(Math.sin(z*7+i))*12:4;c.beginPath();c.moveTo(x+Math.cos(a)*(r+5),y+Math.sin(a)*(r+5));c.lineTo(x+Math.cos(a)*(r+5+len),y+Math.sin(a)*(r+5+len));c.strokeStyle=i%2?'#00f800':'rgba(255,255,255,.75)';c.lineWidth=big?2.2:1.3;c.lineCap='round';c.stroke()}}requestAnimationFrame(frame)}frame()}
animateCanvas($('.v2ai-orb canvas',root));animateCanvas($('.v2ai-bigorb canvas',root),true);
