const $=(s,r=document)=>r.querySelector(s);
const lang=()=>document.documentElement.lang?.toLowerCase().startsWith('es')?'es':'pt';
const WA='5548996752532';
let kb={};
try{kb=await fetch('/knowledge-base.json',{cache:'no-store'}).then(r=>r.json())}catch{}
const copy={pt:{badge:'Converse por voz',title:'V2 AI · Consultor Comercial',ready:'Pronto para conversar',start:'Conversar com V2 AI',stop:'Encerrar conversa',connecting:'Conectando ao Gemini…',listening:'Ouvindo e conversando…',talking:'V2 AI está falando…',placeholder:'Escreva uma mensagem…',note:'Gemini Live · voz em tempo real · atendimento PT/ES',hello:'Olá! Eu sou a V2 AI. Posso entender seu negócio e sugerir onde a V2 Studio pode ajudar. Que tipo de negócio você tem?',fallback:'A voz Gemini ainda não está configurada neste ambiente. Você pode testar por texto e usar a base comercial local.',wa:'Continuar no WhatsApp'},es:{badge:'Conversá por voz',title:'V2 AI · Consultor Comercial',ready:'Listo para conversar',start:'Conversar con V2 AI',stop:'Terminar conversación',connecting:'Conectando con Gemini…',listening:'Escuchando y conversando…',talking:'V2 AI está hablando…',placeholder:'Escribí un mensaje…',note:'Gemini Live · voz en tiempo real · atención PT/ES',hello:'¡Hola! Soy V2 AI. Puedo entender tu negocio y sugerirte dónde V2 Studio puede ayudarte. ¿Qué tipo de negocio tenés?',fallback:'La voz Gemini todavía no está configurada en este entorno. Podés probar por texto usando la base comercial local.',wa:'Continuar por WhatsApp'}};
const t=()=>copy[lang()];
const root=document.createElement('div');root.id='v2ai-root';root.innerHTML=`<div class="v2ai-orb-wrap"><button class="v2ai-orb" aria-label="V2 AI"><span class="v2ai-core"></span></button><div class="v2ai-badge"><b>V2 AI</b> · <span>${t().badge}</span></div></div><section class="v2ai-panel" aria-label="V2 AI"><div class="v2ai-head"><div class="v2ai-mini"></div><div class="v2ai-headtxt"><div class="v2ai-title">${t().title}</div><div class="v2ai-status"><i>●</i> <span>${t().ready}</span></div></div><button class="v2ai-close">×</button></div><div class="v2ai-hero"><div class="v2ai-liveorb"><div class="v2ai-bars"><span></span><span></span><span></span><span></span><span></span></div></div><button class="v2ai-callbtn">🎙 ${t().start}</button><div class="v2ai-kb">Base de conhecimento V2 Studio carregada</div></div><div class="v2ai-messages"></div><div class="v2ai-compose"><input class="v2ai-input" autocomplete="off" placeholder="${t().placeholder}"><button class="v2ai-send">➜</button></div><div class="v2ai-foot">${t().note}</div></section>`;document.body.appendChild(root);
const orb=$('.v2ai-orb',root),panel=$('.v2ai-panel',root),closeBtn=$('.v2ai-close',root),callBtn=$('.v2ai-callbtn',root),msgs=$('.v2ai-messages',root),input=$('.v2ai-input',root),send=$('.v2ai-send',root),status=$('.v2ai-status span',root);
let ws=null,mediaStream=null,micCtx=null,processor=null,inputSource=null,outCtx=null,nextPlay=0,connected=false,sessionReady=false,greeted=false,transcriptBuffer='';
function setStatus(x){status.textContent=x}
function add(text,type='ai',html=false){const d=document.createElement('div');d.className='v2ai-msg '+type;html?d.innerHTML=text:d.textContent=text;msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight;return d}
function waLink(){const summary=[...msgs.querySelectorAll('.v2ai-msg')].slice(-8).map(x=>x.textContent).join(' | ').slice(0,700);return `https://wa.me/${WA}?text=${encodeURIComponent((lang()==='pt'?'Olá! Conversei com a V2 AI. Resumo: ':'Hola! Hablé con V2 AI. Resumen: ')+summary)}`}
function showWA(){if(msgs.querySelector('.v2ai-wa'))return;add(`<a class="v2ai-wa" target="_blank" rel="noopener" href="${waLink()}">${t().wa}</a>`,'ai',true)}
function b64FromInt16(a){const u=new Uint8Array(a.buffer);let s='';const n=32768;for(let i=0;i<u.length;i+=n)s+=String.fromCharCode(...u.subarray(i,i+n));return btoa(s)}
function int16FromB64(s){const bin=atob(s),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return new Int16Array(u.buffer)}
async function playPCM(b64){if(!outCtx)outCtx=new AudioContext({sampleRate:24000});if(outCtx.state==='suspended')await outCtx.resume();const pcm=int16FromB64(b64),buf=outCtx.createBuffer(1,pcm.length,24000),ch=buf.getChannelData(0);for(let i=0;i<pcm.length;i++)ch[i]=pcm[i]/32768;const src=outCtx.createBufferSource();src.buffer=buf;src.connect(outCtx.destination);nextPlay=Math.max(nextPlay,outCtx.currentTime+.02);src.start(nextPlay);nextPlay+=buf.duration;orb.classList.add('talking');setStatus(t().talking);src.onended=()=>{if(outCtx.currentTime>=nextPlay-.05){orb.classList.remove('talking');if(connected)setStatus(t().listening)}}}
function systemPrompt(){return `Você é V2 AI, consultor comercial conversacional da V2 Studio em Florianópolis. Fale de modo humano, breve, profissional e consultivo. Responda sempre no idioma do visitante, português brasileiro ou espanhol rioplatense.\n\nOBJETIVO: entender o negócio e o gargalo, qualificar sem transformar a conversa em interrogatório, recomendar apenas o primeiro passo mais útil e, quando houver intenção real, convidar para continuar no WhatsApp com a equipe V2 Studio. Você NÃO deve pressionar, manipular, inventar preços, inventar cases ou prometer integrações.\n\nORDEM CONVERSACIONAL: 1) descubra tipo de negócio; 2) principal problema; 3) canais atuais; 4) volume aproximado; 5) ferramentas atuais apenas se for relevante; 6) resuma o diagnóstico; 7) recomende um primeiro passo; 8) tire objeções; 9) convide para WhatsApp. Faça no máximo UMA pergunta por resposta e não repita perguntas já respondidas.\n\nREGRAS: fale de resultado antes de falar de tecnologia. Se perguntarem preço, explique o modelo implantação + mensalidade e diga que depende de canais, volume, integrações e complexidade. Para Booking/Airbnb/PMS, diga que integração depende de API e permissões. Sempre preserve atendimento humano. Quando chegar a hora de fechar, mencione claramente a palavra WhatsApp para a interface mostrar o botão de continuidade.\n\nBASE DE CONHECIMENTO OFICIAL:\n${JSON.stringify(kb)}`}
async function getToken(){const r=await fetch('/api/gemini-token',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||'token_error');return d}
async function startMic(){mediaStream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});micCtx=new AudioContext();await micCtx.resume();inputSource=micCtx.createMediaStreamSource(mediaStream);processor=micCtx.createScriptProcessor(2048,1,1);const rate=Math.round(micCtx.sampleRate);processor.onaudioprocess=e=>{if(!ws||ws.readyState!==1||!sessionReady)return;const f=e.inputBuffer.getChannelData(0),pcm=new Int16Array(f.length);for(let i=0;i<f.length;i++){const v=Math.max(-1,Math.min(1,f[i]));pcm[i]=v<0?v*32768:v*32767}ws.send(JSON.stringify({realtimeInput:{audio:{data:b64FromInt16(pcm),mimeType:`audio/pcm;rate=${rate}`}}}))};inputSource.connect(processor);processor.connect(micCtx.destination);orb.classList.add('live');setStatus(t().listening)}
async function startGemini(){if(connected)return;setStatus(t().connecting);callBtn.disabled=true;try{const {token,model}=await getToken();const url=`wss://generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1beta.GenerativeService.BidiGenerateContentConstrained?access_token=${encodeURIComponent(token)}`;ws=new WebSocket(url);ws.onopen=()=>{ws.send(JSON.stringify({setup:{model:`models/${model}`,generationConfig:{responseModalities:['AUDIO'],speechConfig:{voiceConfig:{prebuiltVoiceConfig:{voiceName:'Puck'}}}},systemInstruction:{parts:[{text:systemPrompt()}]},inputAudioTranscription:{},outputAudioTranscription:{},sessionResumption:{}}}))};ws.onmessage=async ev=>{const m=JSON.parse(ev.data);if(m.setupComplete){sessionReady=true;connected=true;panel.classList.add('connected');callBtn.disabled=false;callBtn.classList.add('stop');callBtn.textContent='■ '+t().stop;await startMic();if(!greeted){greeted=true;sendText(t().hello,false)}}const sc=m.serverContent;if(sc?.inputTranscription?.text){const x=sc.inputTranscription.text.trim();if(x)add(x,'user')}if(sc?.outputTranscription?.text){transcriptBuffer+=sc.outputTranscription.text;if(sc.turnComplete){const clean=transcriptBuffer.trim();if(clean){add(clean,'ai');if(/whatsapp/i.test(clean))showWA()}transcriptBuffer=''}}if(sc?.modelTurn?.parts)for(const p of sc.modelTurn.parts)if(p.inlineData?.data)await playPCM(p.inlineData.data);if(sc?.turnComplete){orb.classList.remove('talking');setStatus(t().listening)}};ws.onerror=()=>{add('Gemini Live: erro de conexão.','ai');stopGemini()};ws.onclose=()=>{if(connected)stopGemini(false)}}catch(e){callBtn.disabled=false;setStatus(t().ready);add(t().fallback,'ai');if(!greeted){greeted=true;add(t().hello,'ai');browserSpeak(t().hello)}}}
function stopGemini(closeSocket=true){connected=false;sessionReady=false;panel.classList.remove('connected');orb.classList.remove('live','talking');callBtn.classList.remove('stop');callBtn.textContent='🎙 '+t().start;setStatus(t().ready);if(processor){try{processor.disconnect()}catch{}processor=null}if(inputSource){try{inputSource.disconnect()}catch{}inputSource=null}if(mediaStream){mediaStream.getTracks().forEach(x=>x.stop());mediaStream=null}if(micCtx){micCtx.close().catch(()=>{});micCtx=null}if(closeSocket&&ws){try{ws.close()}catch{}}ws=null}
function sendText(text,showUser=true){text=(text||'').trim();if(!text)return;if(showUser)add(text,'user');input.value='';if(connected&&ws?.readyState===1){ws.send(JSON.stringify({realtimeInput:{text}}));return}localReply(text)}
function localReply(q){const s=q.toLowerCase();let out='';const L=lang();if(/precio|preço|preco|quanto|cuanto|valor|custa/.test(s))out=kb.pricing||'';else if(/airbnb|booking|aluguel|alquiler|tempor|reserva/.test(s))out=kb.segments?.aluguel_temporario||'';else if(/whatsapp|instagram|facebook|canal/.test(s))out='WhatsApp, Instagram e Facebook podem alimentar um único fluxo de atendimento, qualificação e encaminhamento.';else if(/servi|fazem|hacen|ofere/.test(s))out=(kb.services||[]).join(', ');else out=L==='pt'?'Para te orientar bem: qual é o principal problema que você quer resolver hoje — demora no atendimento, perda de leads ou trabalho manual?':'Para orientarte bien: ¿cuál es el principal problema que querés resolver hoy: demora en la atención, pérdida de leads o trabajo manual?';add(out,'ai');browserSpeak(out);if(/whatsapp/i.test(q))showWA()}
function browserSpeak(x){if(!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(x);u.lang=lang()==='pt'?'pt-BR':'es-AR';speechSynthesis.cancel();speechSynthesis.speak(u)}
orb.onclick=()=>{panel.classList.toggle('open');if(panel.classList.contains('open')&&!greeted)add(lang()==='pt'?'Clique em “Conversar com V2 AI” para iniciar uma conversa de voz em tempo real.':'Tocá “Conversar con V2 AI” para iniciar una conversación de voz en tiempo real.','ai')};
closeBtn.onclick=()=>{panel.classList.remove('open');stopGemini()};callBtn.onclick=()=>connected?stopGemini():startGemini();send.onclick=()=>sendText(input.value);input.addEventListener('keydown',e=>{if(e.key==='Enter')sendText(input.value)});window.addEventListener('beforeunload',()=>stopGemini());