const $=(s,r=document)=>r.querySelector(s);
const WA='5548996752532';
const state={lang:document.documentElement.lang?.toLowerCase().startsWith('pt')?'pt':'es',step:0,lead:{company:'',businessType:'',mainPain:'',channels:[],approxVolume:'',currentTools:[],manualTasks:[],expectedResult:'',recommendedFirstAutomation:'',recommendedPackage:'',purchaseIntent:'low',nextStep:''}};
let kb={};try{kb=await fetch('/knowledge-base.json',{cache:'no-store'}).then(r=>r.json())}catch(e){console.warn('KB unavailable',e)}
const c={es:{badge:'Conversá con V2 AI',title:'V2 AI · Asistente Comercial',ready:'Listo para conversar',listen:'Escuchando…',speak:'V2 AI está hablando…',start:'Iniciar conversación',stop:'Detener',placeholder:'Escribí o hablá…',welcome:'Hola, soy V2 AI. ¿Qué tipo de negocio tenés?',lead:'Diagnóstico en vivo',wa:'Continuar por WhatsApp',hint:'Base V2 Studio · voz del navegador · sin API externa',noMic:'Tu navegador no permite reconocimiento de voz. Podés escribir acá abajo.'},pt:{badge:'Converse com a V2 AI',title:'V2 AI · Assistente Comercial',ready:'Pronto para conversar',listen:'Ouvindo…',speak:'V2 AI está falando…',start:'Iniciar conversa',stop:'Parar',placeholder:'Escreva ou fale…',welcome:'Olá, eu sou a V2 AI. Que tipo de negócio você tem?',lead:'Diagnóstico ao vivo',wa:'Continuar no WhatsApp',hint:'Base V2 Studio · voz do navegador · sem API externa',noMic:'Seu navegador não permite reconhecimento de voz. Você pode escrever aqui embaixo.'}};
const t=()=>c[state.lang];
const root=document.createElement('div');root.id='v2ai-root';root.innerHTML=`<div class="v2ai-launch"><button class="v2ai-orb" aria-label="V2 AI"><span class="v2ai-core"></span></button><div class="v2ai-badge"><b>V2 AI</b><span>${t().badge}</span></div></div><section class="v2ai-panel"><header class="v2ai-head"><div class="v2ai-mini"></div><div><strong>${t().title}</strong><small><i>●</i> <span class="v2ai-status">${t().ready}</span></small></div><button class="v2ai-close">×</button></header><div class="v2ai-grid"><div class="v2ai-main"><div class="v2ai-stage"><button class="v2ai-bigorb"><span class="v2ai-stage-core"></span></button><button class="v2ai-call">🎙 ${t().start}</button><small>${t().hint}</small></div><div class="v2ai-messages"></div><div class="v2ai-compose"><input class="v2ai-input" placeholder="${t().placeholder}" autocomplete="off"><button class="v2ai-send">➜</button></div></div><aside class="v2ai-side"><div class="v2ai-side-title"><span>${t().lead}</span><em>LOCAL</em></div><div class="v2ai-lead"></div><button class="v2ai-wa" hidden>${t().wa}</button><button class="v2ai-kb-btn">Base de conocimiento V2 Studio</button></aside></div></section>`;document.body.appendChild(root);
const panel=$('.v2ai-panel',root),orb=$('.v2ai-orb',root),bigOrb=$('.v2ai-bigorb',root),call=$('.v2ai-call',root),status=$('.v2ai-status',root),msgs=$('.v2ai-messages',root),input=$('.v2ai-input',root),send=$('.v2ai-send',root),leadBox=$('.v2ai-lead',root),waBtn=$('.v2ai-wa',root),closeBtn=$('.v2ai-close',root),kbBtn=$('.v2ai-kb-btn',root);
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let rec=null,listening=false;
function add(text,who='ai'){const d=document.createElement('div');d.className='v2ai-msg '+who;d.textContent=text;msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight}
function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=state.lang==='pt'?'pt-BR':'es-AR';u.rate=.98;u.onstart=()=>{status.textContent=t().speak;orb.classList.add('speaking');bigOrb.classList.add('speaking')};u.onend=()=>{orb.classList.remove('speaking');bigOrb.classList.remove('speaking');status.textContent=listening?t().listen:t().ready};window.speechSynthesis.speak(u)}
function reply(text){add(text,'ai');speak(text)}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function has(s,arr){const n=norm(s);return arr.some(x=>n.includes(norm(x)))}
function renderLead(){const L=state.lead;const rows=[[state.lang==='pt'?'Negócio':'Negocio',L.businessType],[state.lang==='pt'?'Dor principal':'Problema principal',L.mainPain],[state.lang==='pt'?'Canais':'Canales',(L.channels||[]).join(', ')],[state.lang==='pt'?'Volume':'Volumen',L.approxVolume],[state.lang==='pt'?'1ª automação':'1ª automatización',L.recommendedFirstAutomation],[state.lang==='pt'?'Pacote':'Paquete',L.recommendedPackage]].filter(x=>x[1]);leadBox.innerHTML=rows.length?rows.map(([k,v])=>`<div><span>${k}</span><b>${String(v)}</b></div>`).join(''):`<p>${state.lang==='pt'?'Ainda coletando informações…':'Todavía recopilando información…'}</p>`;waBtn.hidden=state.lead.purchaseIntent!=='high'&&state.lead.nextStep!=='whatsapp'}
function classifyBusiness(s){if(has(s,['alquiler','aluguel','airbnb','booking','pousada','hospedagem','propiedad','imovel']))return state.lang==='pt'?'Aluguel temporário / hospedagem':'Alquiler temporario / hospedaje';if(has(s,['clinica','dentista','odont','estetica']))return state.lang==='pt'?'Clínica / odontologia':'Clínica / odontología';if(has(s,['turismo','tour','passeio','excursion']))return state.lang==='pt'?'Turismo':'Turismo';if(has(s,['inmobili','imobili']))return state.lang==='pt'?'Imobiliária':'Inmobiliaria';if(has(s,['restaurante','gastronomia','bar','cafe']))return state.lang==='pt'?'Gastronomia':'Gastronomía';return s.trim().slice(0,80)}
function detectChannels(s){const a=[];if(has(s,['whatsapp']))a.push('WhatsApp');if(has(s,['instagram']))a.push('Instagram');if(has(s,['facebook']))a.push('Facebook');if(has(s,['email','e-mail','correo']))a.push('Email');if(has(s,['site','web','chat']))a.push('Web');return a}
function recommend(){const L=state.lead,b=norm(L.businessType+' '+L.mainPain);if(has(b,['alquiler','aluguel','airbnb','booking','hosped'])){L.recommendedFirstAutomation=state.lang==='pt'?'Atendimento inicial + qualificação de imóvel, datas e hóspedes':'Atención inicial + calificación de propiedad, fechas y huéspedes';L.recommendedPackage='Atendimento IA'}else if(has(b,['clinica','odont','dent','estet'])){L.recommendedFirstAutomation=state.lang==='pt'?'FAQ + qualificação + encaminhamento para agenda':'FAQ + calificación + derivación a agenda';L.recommendedPackage='Atendimento IA'}else if(has(b,['manual','planilha','planilla','crm','follow'])){L.recommendedFirstAutomation=state.lang==='pt'?'Automatizar o processo manual mais repetitivo':'Automatizar el proceso manual más repetitivo';L.recommendedPackage='Automação Comercial'}else{L.recommendedFirstAutomation=state.lang==='pt'?'Automatizar a primeira resposta e qualificação de leads':'Automatizar la primera respuesta y calificación de leads';L.recommendedPackage='Atendimento IA'}renderLead()}
function processUser(text){add(text,'user');const n=norm(text);if(has(n,['precio','preco','presupuesto','orcamento','propuesta','proposta','empezar','comecar','humano','persona','whatsapp'])){state.lead.purchaseIntent='high';state.lead.nextStep='whatsapp';recommend();reply(state.lang==='pt'?'Perfeito. Já temos um bom ponto de partida. Posso te encaminhar para a equipe da V2 Studio pelo WhatsApp.':'Perfecto. Ya tenemos un buen punto de partida. Puedo pasarte con el equipo de V2 Studio por WhatsApp.');return}
if(state.step===0){state.lead.businessType=classifyBusiness(text);state.step=1;renderLead();reply(state.lang==='pt'?'Entendi. Qual é o principal problema que você quer resolver hoje?':'Entiendo. ¿Cuál es el principal problema que querés resolver hoy?');return}
if(state.step===1){state.lead.mainPain=text.trim().slice(0,160);state.step=2;renderLead();reply(state.lang==='pt'?'Por quais canais entram hoje a maioria das consultas?':'¿Por qué canales llegan hoy la mayoría de las consultas?');return}
if(state.step===2){state.lead.channels=detectChannels(text);if(!state.lead.channels.length)state.lead.channels=[text.trim().slice(0,80)];state.step=3;renderLead();reply(state.lang==='pt'?'Mais ou menos quantas consultas vocês recebem por dia ou por semana?':'Más o menos, ¿cuántas consultas reciben por día o por semana?');return}
if(state.step===3){state.lead.approxVolume=text.trim().slice(0,80);state.step=4;recommend();reply(state.lang==='pt'?`Pelo que você me contou, eu começaria por ${state.lead.recommendedFirstAutomation.toLowerCase()}. Isso ataca primeiro o ponto mais repetitivo sem tentar automatizar tudo de uma vez. Faz sentido começar por aí?`:`Por lo que me contaste, yo empezaría por ${state.lead.recommendedFirstAutomation.toLowerCase()}. Eso ataca primero lo más repetitivo sin intentar automatizar todo de una vez. ¿Te hace sentido empezar por ahí?`);return}
if(has(n,['si','sí','sim','dale','ok','claro','faz','sentido'])){state.lead.purchaseIntent='high';state.lead.nextStep='whatsapp';renderLead();reply(state.lang==='pt'?'Ótimo. Quer continuar esse diagnóstico com a equipe da V2 Studio pelo WhatsApp?':'Perfecto. ¿Querés continuar este diagnóstico con el equipo de V2 Studio por WhatsApp?');return}
if(has(n,['caro','expensive'])){reply(state.lang==='pt'?'Pode ser caro se não gerar retorno. Primeiro medimos quanto custa hoje o processo manual; se não fizer sentido econômico, não recomendamos.':'Puede ser caro si no genera retorno. Primero medimos cuánto cuesta hoy el proceso manual; si no tiene sentido económico, no lo recomendamos.');return}
if(has(n,['crm'])){reply(state.lang==='pt'?'Se o CRM funciona, melhor. A ideia é conectar e eliminar tarefas manuais ao redor, não substituí-lo sem necessidade.':'Si el CRM funciona, mejor. La idea es conectarlo y eliminar tareas manuales alrededor, no reemplazarlo sin necesidad.');return}
if(has(n,['airbnb','booking','pms','channel'])){reply(state.lang==='pt'?'Pode ser possível, mas depende da disponibilidade da API e das permissões da conta. Primeiro precisamos validar a ferramenta usada.':'Puede ser posible, pero depende de la disponibilidad de la API y de los permisos de la cuenta. Primero hay que validar la herramienta que usan.');return}
reply(state.lang==='pt'?'Posso continuar o diagnóstico com base nas informações da V2 Studio. O que mais pesa hoje: demora no atendimento ou trabalho manual repetitivo?':'Puedo seguir el diagnóstico con la información de V2 Studio. ¿Qué pesa más hoy: la demora en responder o el trabajo manual repetitivo?')}
function startRecognition(){if(!SR){reply(t().noMic);return}if(rec){try{rec.stop()}catch{}}rec=new SR();rec.lang=state.lang==='pt'?'pt-BR':'es-AR';rec.continuous=true;rec.interimResults=false;rec.onresult=e=>{const tx=e.results[e.results.length-1][0].transcript.trim();if(tx)processUser(tx)};rec.onerror=()=>{};rec.onend=()=>{if(listening){try{rec.start()}catch{}}};try{rec.start();listening=true;status.textContent=t().listen;orb.classList.add('listening');bigOrb.classList.add('listening');call.textContent='■ '+t().stop}catch{}}
function stopRecognition(){listening=false;if(rec){try{rec.stop()}catch{}}orb.classList.remove('listening');bigOrb.classList.remove('listening');status.textContent=t().ready;call.textContent='🎙 '+t().start}
function toggleVoice(){if(listening){stopRecognition();return}panel.classList.add('open');reply(t().welcome);setTimeout(startRecognition,500)}
function openWA(){const L=state.lead;const msg=state.lang==='pt'?`Olá V2 Studio. Falei com a V2 AI. Negócio: ${L.businessType||'-'}. Dor: ${L.mainPain||'-'}. Canais: ${(L.channels||[]).join(', ')||'-'}. Volume: ${L.approxVolume||'-'}. Sugestão: ${L.recommendedFirstAutomation||'-'}.`:`Hola V2 Studio. Hablé con V2 AI. Negocio: ${L.businessType||'-'}. Problema: ${L.mainPain||'-'}. Canales: ${(L.channels||[]).join(', ')||'-'}. Volumen: ${L.approxVolume||'-'}. Sugerencia: ${L.recommendedFirstAutomation||'-'}.`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,'_blank','noopener')}
orb.onclick=()=>panel.classList.toggle('open');bigOrb.onclick=toggleVoice;call.onclick=toggleVoice;closeBtn.onclick=()=>panel.classList.remove('open');send.onclick=()=>{const v=input.value.trim();if(v){input.value='';processUser(v)}};input.addEventListener('keydown',e=>{if(e.key==='Enter')send.click()});waBtn.onclick=openWA;kbBtn.onclick=()=>reply(state.lang==='pt'?'Uso somente a base oficial da V2 Studio carregada nesta página.':'Uso solamente la base oficial de V2 Studio cargada en esta página.');
setInterval(()=>{const l=document.documentElement.lang?.toLowerCase().startsWith('pt')?'pt':'es';if(l!==state.lang){state.lang=l;input.placeholder=t().placeholder;renderLead()}},800);renderLead();