const $=(s,r=document)=>r.querySelector(s);
const WA='5548996752532';
const state={lang:document.documentElement.lang?.toLowerCase().startsWith('pt')?'pt':'es',lead:{company:'',businessType:'',mainPain:'',channels:[],approxVolume:'',currentTools:[],manualTasks:[],expectedResult:'',recommendedFirstAutomation:'',recommendedPackage:'',purchaseIntent:'low',nextStep:''},messages:[],listening:false,busy:false};
let kb={};try{kb=await fetch('/knowledge-base.json',{cache:'no-store'}).then(r=>r.json())}catch{}

const copy={es:{badge:'Conversá con V2 AI',title:'V2 AI · Agente Comercial',ready:'Listo para conversar',listening:'Escuchando…',thinking:'Analizando tu negocio…',speaking:'V2 AI está hablando…',start:'Hablar',stop:'Detener',placeholder:'Escribí o hablá…',welcome:'Hola, soy V2 AI. Puedo entender cómo funciona tu negocio y mostrarte dónde V2 Studio podría ayudarte. ¿Qué tipo de negocio tenés?',lead:'Diagnóstico en vivo',wa:'Continuar por WhatsApp',kb:'Base de conocimiento V2 Studio',hint:'Agente OpenAI · voz del navegador · PT/ES',noSpeech:'No pude escuchar nada. Probá de nuevo o escribime acá.',noMic:'El navegador no pudo acceder al micrófono. También podés escribir.'},pt:{badge:'Converse com a V2 AI',title:'V2 AI · Agente Comercial',ready:'Pronto para conversar',listening:'Ouvindo…',thinking:'Analisando seu negócio…',speaking:'V2 AI está falando…',start:'Falar',stop:'Parar',placeholder:'Escreva ou fale…',welcome:'Olá, eu sou a V2 AI. Posso entender como seu negócio funciona e mostrar onde a V2 Studio pode ajudar. Que tipo de negócio você tem?',lead:'Diagnóstico ao vivo',wa:'Continuar no WhatsApp',kb:'Base de conhecimento V2 Studio',hint:'Agente OpenAI · voz do navegador · PT/ES',noSpeech:'Não consegui ouvir. Tente novamente ou escreva aqui.',noMic:'O navegador não conseguiu acessar o microfone. Você também pode escrever.'}};
const t=()=>copy[state.lang];
const root=document.createElement('div');root.id='v2ai-root';root.innerHTML=`<div class="v2ai-launch"><button class="v2ai-orb" aria-label="V2 AI"><span class="v2ai-core"></span></button><div class="v2ai-badge"><b>V2 AI</b><span>${t().badge}</span></div></div><section class="v2ai-panel"><header class="v2ai-head"><div class="v2ai-mini"></div><div><strong>${t().title}</strong><small><i>●</i> <span class="v2ai-status">${t().ready}</span></small></div><button class="v2ai-close">×</button></header><div class="v2ai-grid"><div class="v2ai-main"><div class="v2ai-stage"><button class="v2ai-bigorb"><span class="v2ai-stage-core"></span></button><button class="v2ai-call">🎙 ${t().start}</button><small>${t().hint}</small></div><div class="v2ai-messages"></div><div class="v2ai-compose"><input class="v2ai-input" placeholder="${t().placeholder}" autocomplete="off"><button class="v2ai-send">➜</button></div></div><aside class="v2ai-side"><div class="v2ai-side-title"><span>${t().lead}</span><em>LIVE</em></div><div class="v2ai-lead"></div><button class="v2ai-wa" hidden>${t().wa}</button><button class="v2ai-kb-btn">${t().kb}</button></aside></div></section>`;document.body.appendChild(root);
const panel=$('.v2ai-panel',root),orb=$('.v2ai-orb',root),bigOrb=$('.v2ai-bigorb',root),call=$('.v2ai-call',root),statusEl=$('.v2ai-status',root),msgs=$('.v2ai-messages',root),input=$('.v2ai-input',root),send=$('.v2ai-send',root),leadBox=$('.v2ai-lead',root),waBtn=$('.v2ai-wa',root),closeBtn=$('.v2ai-close',root),kbBtn=$('.v2ai-kb-btn',root);

function setStatus(s){statusEl.textContent=s}
function addMessage(text,who='ai'){if(!text)return;state.messages.push({who,text});const d=document.createElement('div');d.className='v2ai-msg '+who;d.textContent=text;msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function packageLabel(v){return v==='pacote_1'?'Presença & Atendimento':v==='pacote_2'?'Business Automation':v==='pacote_3'?'Ecossistema Digital & IA':''}
function intentLabel(v){return state.lang==='pt'?({low:'Baixa',medium:'Média',high:'Alta'}[v]||v):({low:'Baja',medium:'Media',high:'Alta'}[v]||v)}
function renderLead(){const L=state.lead;const rows=[[state.lang==='pt'?'Negócio':'Negocio',L.businessType||L.company],[state.lang==='pt'?'Dor principal':'Problema principal',L.mainPain],[state.lang==='pt'?'Canais':'Canales',(L.channels||[]).join(', ')],[state.lang==='pt'?'Volume':'Volumen',L.approxVolume],[state.lang==='pt'?'Ferramentas':'Herramientas',(L.currentTools||[]).join(', ')],[state.lang==='pt'?'1ª automação':'1ª automatización',L.recommendedFirstAutomation],[state.lang==='pt'?'Pacote':'Paquete',packageLabel(L.recommendedPackage)],[state.lang==='pt'?'Intenção':'Intención',intentLabel(L.purchaseIntent)]].filter(x=>x[1]);leadBox.innerHTML=rows.length?rows.map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join(''):`<p>${state.lang==='pt'?'Ainda coletando informações…':'Todavía recopilando información…'}</p>`;waBtn.hidden=!(L.purchaseIntent==='high'||L.nextStep==='whatsapp')}
function mergeLead(obj={}){for(const k of Object.keys(state.lead)){const v=obj[k];if(v===undefined||v===null||v==='')continue;if(Array.isArray(v)){if(v.length)state.lead[k]=[...new Set([...(state.lead[k]||[]),...v])]}else state.lead[k]=v}renderLead();try{sessionStorage.setItem('v2ai-openai-lead',JSON.stringify(state.lead))}catch{}}
try{const saved=JSON.parse(sessionStorage.getItem('v2ai-openai-lead')||'null');if(saved)state.lead={...state.lead,...saved}}catch{}renderLead();

function whatsapp(){const L=state.lead;const summary=`V2 AI Lead\nNegocio: ${L.businessType||L.company||'-'}\nProblema: ${L.mainPain||'-'}\nCanales: ${(L.channels||[]).join(', ')||'-'}\nVolumen: ${L.approxVolume||'-'}\nAutomatización sugerida: ${L.recommendedFirstAutomation||'-'}\nIntención: ${L.purchaseIntent||'-'}`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(summary)}`,'_blank','noopener')}

function speak(text){if(!('speechSynthesis' in window)||!text)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=state.lang==='pt'?'pt-BR':'es-AR';u.rate=1.02;u.pitch=1;u.onstart=()=>{orb.classList.add('speaking');bigOrb.classList.add('speaking');setStatus(t().speaking)};u.onend=()=>{orb.classList.remove('speaking');bigOrb.classList.remove('speaking');setStatus(t().ready)};window.speechSynthesis.speak(u)}

async function ask(message,voice=true){if(state.busy||!message.trim())return;state.busy=true;send.disabled=true;input.disabled=true;addMessage(message,'user');setStatus(t().thinking);try{const r=await fetch('/api/openai-agent',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message,history:state.messages.slice(0,-1),lead:state.lead,kb,lang:state.lang})});const data=await r.json();if(!r.ok)throw new Error(data?.message||data?.error||'OpenAI error');mergeLead(data.lead||{});if(data.handoff){state.lead.nextStep='whatsapp';waBtn.hidden=false;renderLead()}addMessage(data.reply,'ai');if(voice)speak(data.reply);else setStatus(t().ready)}catch(e){console.error(e);const msg=state.lang==='pt'?'Não consegui responder agora. Tente novamente em alguns segundos.':'No pude responder ahora. Probá nuevamente en unos segundos.';addMessage(msg,'ai');setStatus(t().ready)}finally{state.busy=false;send.disabled=false;input.disabled=false;input.focus()}}

const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null;
function startRecognition(){if(!SR){addMessage(t().noMic,'ai');return}if(state.listening){try{recognition?.stop()}catch{}return}window.speechSynthesis?.cancel();recognition=new SR();recognition.lang=state.lang==='pt'?'pt-BR':'es-AR';recognition.interimResults=false;recognition.continuous=false;recognition.maxAlternatives=1;recognition.onstart=()=>{state.listening=true;orb.classList.add('listening');bigOrb.classList.add('listening');call.textContent='■ '+t().stop;setStatus(t().listening)};recognition.onresult=e=>{const txt=e.results?.[0]?.[0]?.transcript?.trim();if(txt)ask(txt,true);else addMessage(t().noSpeech,'ai')};recognition.onerror=e=>{console.warn('speech recognition',e.error);if(e.error!=='aborted')addMessage(e.error==='not-allowed'?t().noMic:t().noSpeech,'ai')};recognition.onend=()=>{state.listening=false;orb.classList.remove('listening');bigOrb.classList.remove('listening');call.textContent='🎙 '+t().start;if(!state.busy)setStatus(t().ready)};try{recognition.start()}catch(e){console.warn(e)}}

orb.onclick=()=>{panel.classList.toggle('open');if(panel.classList.contains('open')&&!state.messages.length){addMessage(t().welcome,'ai');speak(t().welcome)}};closeBtn.onclick=()=>panel.classList.remove('open');call.onclick=startRecognition;bigOrb.onclick=startRecognition;send.onclick=()=>{const v=input.value.trim();if(v){input.value='';ask(v,true)}};input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();send.click()}};waBtn.onclick=whatsapp;kbBtn.onclick=()=>addMessage(state.lang==='pt'?'Minha base inclui serviços, nichos, objeções, qualificação, pacotes e regras comerciais da V2 Studio.':'Mi base incluye servicios, nichos, objeciones, calificación, paquetes y reglas comerciales de V2 Studio.','ai');
setInterval(()=>{const next=document.documentElement.lang?.toLowerCase().startsWith('pt')?'pt':'es';if(next!==state.lang){state.lang=next;input.placeholder=t().placeholder;waBtn.textContent=t().wa;kbBtn.textContent=t().kb;renderLead()}},1000);
